config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :microposts, only: [:index, :create, :show, :update, :destroy]
    end
  end

  get 'sessions/new'

  root 'static_pages#home'

  get '/acb', :to => redirect("/acb.html")

  get 'about' => 'static_pages#about'
  get 'callback' => 'static_pages#callback'
  get 'new_user' => 'users#new'

  get 'dropbox' => 'dropbox#index'
  get 'dropbox_authorize' => 'dropbox#authorize'
  get 'dropbox_callback' => 'dropbox#dropbox_callback'
  get 'dropbox_deauthorize' => 'dropbox#deauthorize'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
end

app/views/layouts/_footer.html.erb
  <footer class="footer">
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "AMC :: STB Dashboard", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "ACB Calculator", "/acb.html", :target => "_blank" %></li>
            <% if current_user.dropbox_session %>
              <li><%= link_to "Dropbox", dropbox_path %></li>
            <% else %>
              <li><%= link_to "Link Dropbox", dropbox_path %></li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Users", users_path %></li>
                <% if current_user.dropbox_session %>
                  <li><%= link_to "Unlink Dropbox", dropbox_deauthorize_path %></li>
                <% end %>
                <% if current_user.admin? %>
                  <li><%= link_to "New user", new_user_path %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html15.min.js"></script>
  <![endif]-->

app/views/layouts/_user.html.erb
<% if (not @user.nil?) && (not @user.email.nil?) %>
  <%= gravatar_for @user %>
  <%= @user.name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AMC :: STB Dashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container main">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>